# -*- coding: utf-8 -*-
"""RewardPrediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17uC-CSV9C1ueUnws9dQdGskk8sFRGb8b
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt #importing libraries
from sklearn.ensemble import RandomForestRegressor

df=pd.read_csv("block_data.csv")
df

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('timestamp(seconds)')
plt.ylabel('blockreward(ether)')
plt.scatter(df.timestamp,df.blockReward,color="Red",marker=".")

model=RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(df.timestamp.values.reshape(-1,1),df.blockReward.values.ravel())

new_timestamp=np.array([[1686639527]])
predicted_blockReward=model.predict(new_timestamp)
plt.scatter(df.timestamp, df.blockReward, label="Data points")
plt.scatter(new_timestamp, predicted_blockReward, color='red', label='Predicetd Future Block Reward')
plt.xlabel('Timestamp')
plt.ylabel('Block Reward')
plt.legend()
plt.show()
print("Predicted Block Reward: ", predicted_blockReward[0])